% test script to test images for facial expression

% just add or remove the name of the images below for testing
% Below image names are of each expression of mixed models 

% Currently script uses the Mahalanobis distance to compare feature points
% To use Euclidean distance, update line:46 in cv_pro_trainAndTest.m and create new training "trained.mat" file

cv_pro_testImgs(	'KR.AN3.85.tiff', ... 
            'NA.AN2.212.tiff', ...
		  	'KA.DI1.42.tiff', ...
		  	'TM.DI2.194.tiff', ...
            'KL.HA2.159.tiff', ...
            'NA.HA3.204.tiff', ...
            'NA.SA2.206.tiff', ...
            'UY.SA3.142.tiff', ...
            'KA.SU2.37.tiff', ...
            'UY.SU2.144.tiff', ...
            'NA.FE2.218.tiff', ...
            'TM.FE2.197.tiff', ...
		  	'KA.NE2.27.tiff', ...
            'NM.NE2.93.tiff' ...
		  	)
